apiVersion: v1
kind: Service
metadata:
    name: "knpchdev-5073"
    labels:
        app: "knpchdev-5073"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "knpchdev-5073"